import React from 'react'

function About(){
    return(
        <div>
            <h1>About Kanye West</h1>
            <p className="paragraph">Born June 8, 1977 (age 44) Kanye is one of the most successful artists in Grammy Awards history.Kanye West initially made his mark on the music industry as a producer for leading artists. He showcased his own abilities as a rapper with his 2004 debut, College Dropout, and cemented his place atop the hip hop world via such chart-topping albums as Late Registration (2005), My Beautiful Dark Twisted Fantasy (2010), Yeezus (2013) and Ye (2018). The winner of nearly two dozen Grammy Awards, West is also known for his awards-show theatrics, forays into fashion and marriage to Kim Kardashian.</p>
            <p className="paragraph">His father, Ray, was a photojournalist for the Atlanta Journal newspaper and was also politically active in the Black Panthers; he later became a Christian counselor. West's mother, Donda, was a teacher who became a professor of English at Chicago State University, and eventually, her son's manager before she died at the age of 58 from heart disease after cosmetic surgery in 2007. Her passing would profoundly affect West musically as well as personally.</p>
            <p className="paragraph">Ray and Donda divorced amicably when West was three. After that he was raised on Chicago's middle-class South Shore neighborhood by his mother, and spent summers with his father. At the age of 10, West moved for a year with Donda to China, where she taught as part of a university-exchange program; he was the only foreigner in his class. After returning to Chicago, West was drawn to the South Side's hip-hop scene, and he befriended the DJ and producer No I.D., who became his mentor. West graduated from Polaris High School and won a scholarship to study at Chicago's American Academy of Art — but dropped out of college altogether to pursue music, an act that would inform the title of his first solo album years later.</p>
            <p className="paragraph">After spending time producing for local artists, West developed a signature style, dubbed "chipmunk soul," characterized by sped-up soul samples. He then moved to New York in 2001. Here he got his big break handling the production for the Jay-Z track "This Can't Be Life," which appeared on the 2000 album Dynasty: Roc La Familia. The following year he cemented his burgeoning reputation by producing four songs on Jay Z's The Blueprint, widely regarded as one of the greatest rap albums of all time. From there, West went on to produce for other stellar talents, including the rappers Mos Def, Talib Kweli and Ludacris, and the singers Alicia Keys and Beyoncé.</p>
            <p className="paragraph">But West was not content to be a backroom player. He wanted to be the headline act but initially struggled to be taken seriously as a rapper. He pleaded with Roc-A-Fella records to let him rap, but as co-founder Jay-Z later told Time magazine, "We all grew up street guys who had to do whatever we had to do to get by. Then there's Kanye, who to my knowledge has never hustled a day in his life. I didn't see how it could work." West got a similar response from other labels. "I'd leave meetings crying all the time," he recalled.</p>
            <p className="paragraph">With reluctance, Damon Dash signed West to Roc-A-Fella in 2002, but he did so mostly to retain him as a producer. That October, as West was driving home from a recording session in a California studio, he was involved in a head-on car collision that left him with a shattered jaw. He wrote and recorded a song about the experience, "Through the Wire," with his jaw still wired shut following reconstructive surgery. He then wrote much of the rest of his debut album while recuperating in L.A. But once the album was complete, it was leaked online. In response, West decided to make it better: he revised and rewrote songs and refined the production, adding stronger drums, gospel choirs and strings (he paid for orchestras out of his own pocket).</p>
            <p className="paragraph">The album was finally released in February 2004 — it sold 2.6 million copies and made West a star. Titled The College Dropout, it broke the gangsta-rap mold, with themes including consumerism (he was critical of it back then), racism, higher education and his religious beliefs. On the single "Jesus Walks" he rapped, "They say you can rap about anything except for Jesus/That means guns, sex, lies, videotapes/But if I talk about God, my record won't get played." The College Dropout peaked at No. 2 on the Billboard Hot 200 chart, and West received 10 Grammy nominations, winning three awards including Best Rap Song for "Jesus Walks" and Best Rap Album. Shortly after the album was released, West founded his record label, GOOD music — an acronym for Getting Out Our Dreams — in conjunction with Sony BMG. He would put out music by John Legend, Big Sean, Common, Pusha-T and more.</p>
            <a id="anchor" href="https://www.biography.com/musician/kanye-west">To continue reading head over to this link...</a>
        </div>
    )
}

export default About